PassEnv APP_ENV
PassEnv APP_DEBUG
PassEnv APP_NAME
PassEnv APP_URL
PassEnv LOG_CHANNEL
PassEnv DB_CONNECTION
PassEnv DATABASE_URL
PassEnv DB_URL
PassEnv SESSION_DRIVER
PassEnv CACHE_STORE
PassEnv QUEUE_CONNECTION
